<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PromoHunter.Worker-eba0c027-2463-4d40-a769-7d34ace8f9cf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PromoHunter.Application\PromoHunter.Application.csproj" />
    <ProjectReference Include="..\PromoHunter.Infrastructure\PromoHunter.Infrastructure.csproj" />
  </ItemGroup>
</Project>
